### ISSUE TITLE
build fails: HMAC_CTX_* undeclared in crypto.h

### ISSUE THREAD

**Issue by SimonN** [MonaSolutions/MonaServer#56]
Hi,

I'm trying to build MonaServer from github, master, commit `c2397e379`.

I use Arch Linux on x86_64 with g++ version 6.3.1. I've installed LuaJIT 2.0.4 and OpenSSL 1.1.0.e-1 via Arch packages. (In particular, I have `/usr/include/openssl/hmac.h` installed).

Nonetheless, `make` on MonaServer fails with the error below. Am I missing dependencies? Is it possible to build MonaServer with OpenSSL 1.1, or do you assume OpenSSL 1.0?

```
In file included from sources/Crypto.cpp:20:0:
./include/Mona/Crypto.h:44:12: error: field ‘_hmacCTX’ has incomplete type ‘HMAC_CTX {aka hmac_ctx_st}’
   HMAC_CTX _hmacCTX;
            ^~~~~~~~
In file included from /usr/include/openssl/evp.h:14:0,
                 from /usr/include/openssl/hmac.h:15,
                 from ./include/Mona/Crypto.h:24,
                 from sources/Crypto.cpp:20:
/usr/include/openssl/ossl_typ.h:102:16: note: forward declaration of ‘HMAC_CTX {aka struct hmac_ctx_st}’
 typedef struct hmac_ctx_st HMAC_CTX;
                ^~~~~~~~~~~
In file included from sources/Crypto.cpp:20:0:
./include/Mona/Crypto.h: In constructor ‘Mona::Crypto::HMAC::HMAC()’:
./include/Mona/Crypto.h:38:35: error: ‘HMAC_CTX_init’ was not declared in this scope
   HMAC() { HMAC_CTX_init(&_hmacCTX); }
                                   ^
./include/Mona/Crypto.h: In destructor ‘virtual Mona::Crypto::HMAC::~HMAC()’:
./include/Mona/Crypto.h:39:47: error: ‘HMAC_CTX_cleanup’ was not declared in this scope
   virtual ~HMAC() { HMAC_CTX_cleanup(&_hmacCTX); }
                                               ^
make[2]: *** [Makefile:48: tmp/Release/Crypto.o] Error 1
```

**Comment by thomasjammet** [comment]
Yes it should work with Openssl 1.0, 

I will take a look at this class ASAP to make it work with OpenSSL 1.1

**Comment by SimonN** [comment]
Thanks for looking at it!

I don't need an urgent solution. We wanted to stream video via RTMP from machine A to B, receive that on B with MonaServer, then stream from B to twitch a composed video with A and B. Our hackish solution was to stream A's entire desktop with VLC and receive it on B with VLC.

I'll keep an eye on MonaServer still, it sounds like a proper solution for this problem.

**Comment by thomasjammet** [comment]
Ok, I have read that OpenSSL 1.0 versions will be maintained since 2019 so there is no hurry to migrate to 1.1, I will let this ticket open to do the migration later.

Have you tried to use [OBS Studio](https://obsproject.com/)? It's a great broadcasting tool which allow to customize your stream easily.
